#!/usr/bin/env bash
#
# harden.sh — Linux shell hardening tool
#
# What it does:
#   1. Generates a passphrase-protected SSH key pair for the user
#   2. Adds the public key to authorized_keys on the server
#   3. Configures sshd for pubkey-only auth on port 2223
#   4. Installs UFW and blocks everything except the SSH port
#
# Usage:
#   sudo bash harden.sh [username]
#
#   username — the login user to generate keys for (defaults to $SUDO_USER)
#

set -euo pipefail

# ─── colours ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

SSH_PORT=2223
SSHD_CONFIG="/etc/ssh/sshd_config"
SSHD_CONFIG_BACKUP="/etc/ssh/sshd_config.bak.$(date +%Y%m%d%H%M%S)"

# ─── helpers ────────────────────────────────────────────────────────────────────

log_info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[ OK ]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_err()   { echo -e "${RED}[ERR ]${NC}  $*"; }

bail() {
    log_err "$*"
    exit 1
}

# ─── pre-flight checks ─────────────────────────────────────────────────────────

preflight() {
    if [[ $EUID -ne 0 ]]; then
        bail "This script must be run as root (use sudo)."
    fi

    if ! command -v ssh-keygen &>/dev/null; then
        bail "ssh-keygen not found. Install openssh-client first."
    fi

    # Install openssh-server if not present
    if ! command -v sshd &>/dev/null; then
        log_warn "openssh-server not installed — installing now..."
        if command -v apt-get &>/dev/null; then
            apt-get update -qq && apt-get install -y -qq openssh-server
        elif command -v dnf &>/dev/null; then
            dnf install -y -q openssh-server
        elif command -v yum &>/dev/null; then
            yum install -y -q openssh-server
        elif command -v pacman &>/dev/null; then
            pacman -Sy --noconfirm openssh
        else
            bail "No supported package manager found — install openssh-server manually."
        fi
        log_ok "openssh-server installed."
    fi

    # Determine target user
    TARGET_USER="${1:-${SUDO_USER:-}}"
    if [[ -z "$TARGET_USER" ]]; then
        bail "Cannot determine target user. Pass username as first argument."
    fi

    TARGET_HOME=$(eval echo "~${TARGET_USER}")
    if [[ ! -d "$TARGET_HOME" ]]; then
        bail "Home directory for user '${TARGET_USER}' not found at ${TARGET_HOME}."
    fi

    log_info "Target user : ${TARGET_USER}"
    log_info "Home dir    : ${TARGET_HOME}"
    log_info "SSH port    : ${SSH_PORT}"
}

# ─── step 1: generate passphrase-protected key pair ─────────────────────────────

generate_key() {
    log_info "──── Generating SSH Key ────"

    USER_SSH_DIR="${TARGET_HOME}/.ssh"
    mkdir -p "$USER_SSH_DIR"
    chmod 700 "$USER_SSH_DIR"

    USER_KEY="${USER_SSH_DIR}/hardened"
    if [[ ! -f "$USER_KEY" ]]; then
        echo ""
        log_info "You will be asked to set a passphrase for your SSH key."
        log_info "This passphrase is required every time you connect."
        echo ""
        # Run ssh-keygen as the target user so the passphrase prompt works
        sudo -u "${TARGET_USER}" ssh-keygen -t ed25519 -f "$USER_KEY" -C "${TARGET_USER}@$(hostname)"
        log_ok "Key pair created at ${USER_KEY}"
    else
        log_warn "Key ${USER_KEY} already exists — skipping generation."
    fi

    # Add public key to authorized_keys
    AUTH_KEYS="${USER_SSH_DIR}/authorized_keys"
    PUB_KEY=$(cat "${USER_KEY}.pub")

    if [[ -f "$AUTH_KEYS" ]] && grep -qF "$PUB_KEY" "$AUTH_KEYS"; then
        log_warn "Public key already in authorized_keys — skipping."
    else
        echo "$PUB_KEY" >> "$AUTH_KEYS"
        log_ok "Public key added to authorized_keys."
    fi

    # Fix permissions
    chmod 600 "$AUTH_KEYS" "$USER_KEY"
    chmod 644 "${USER_KEY}.pub"
    chown -R "${TARGET_USER}:${TARGET_USER}" "$USER_SSH_DIR"

    log_ok "SSH key setup complete."
}

# ─── step 2: harden sshd_config ────────────────────────────────────────────────

configure_sshd() {
    log_info "──── Configuring SSHD ────"

    # Back up current config (if it exists)
    if [[ -f "$SSHD_CONFIG" ]]; then
        cp "$SSHD_CONFIG" "$SSHD_CONFIG_BACKUP"
        log_info "Backup saved to ${SSHD_CONFIG_BACKUP}"
    else
        log_warn "No existing sshd_config found — creating from scratch."
        SSHD_CONFIG_BACKUP="(none — fresh install)"
    fi

    # Build a clean hardened config
    cat > "$SSHD_CONFIG" <<EOF
# ─── Hardened sshd_config ── generated by harden.sh $(date +%Y-%m-%d) ──────────

# ── Network ──────────────────────────────────────────────────────────────────────
Port ${SSH_PORT}
AddressFamily inet
ListenAddress 0.0.0.0

# ── Authentication ───────────────────────────────────────────────────────────────
PermitRootLogin no
MaxAuthTries 3
MaxSessions 3

# Pubkey-only auth
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Disable all other auth methods
PasswordAuthentication no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM no
PermitEmptyPasswords no

# ── Security hardening ───────────────────────────────────────────────────────────
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
GatewayPorts no
PrintMotd no
TCPKeepAlive yes
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 30
StrictModes yes
IgnoreRhosts yes

# ── Logging ──────────────────────────────────────────────────────────────────────
SyslogFacility AUTH
LogLevel VERBOSE

# ── Allowed algorithms (modern only) ────────────────────────────────────────────
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
HostKeyAlgorithms ssh-ed25519

# ── Subsystems ───────────────────────────────────────────────────────────────────
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

    # Ensure privilege separation directory exists
    if [[ ! -d /run/sshd ]]; then
        mkdir -p /run/sshd
        chmod 0755 /run/sshd
        log_ok "Created /run/sshd (privilege separation directory)."
    fi

    # Validate config before restarting
    if sshd -t -f "$SSHD_CONFIG"; then
        log_ok "sshd_config syntax is valid."
    else
        log_err "sshd_config syntax check FAILED — rolling back."
        if [[ -f "$SSHD_CONFIG_BACKUP" ]]; then
            cp "$SSHD_CONFIG_BACKUP" "$SSHD_CONFIG"
            bail "Reverted to backup. Fix issues and re-run."
        else
            rm -f "$SSHD_CONFIG"
            bail "Removed invalid config. Fix issues and re-run."
        fi
    fi

    # Restart (or start) sshd
    if systemctl is-active --quiet sshd 2>/dev/null; then
        systemctl restart sshd
    elif systemctl is-active --quiet ssh 2>/dev/null; then
        systemctl restart ssh
    elif systemctl list-unit-files sshd.service &>/dev/null; then
        systemctl enable --now sshd
    elif systemctl list-unit-files ssh.service &>/dev/null; then
        systemctl enable --now ssh
    else
        log_warn "Could not detect sshd service name — please start SSH manually."
    fi

    log_ok "SSHD configured and restarted on port ${SSH_PORT}."
}

# ─── step 3: install & configure UFW ───────────────────────────────────────────

configure_firewall() {
    log_info "──── Configuring Firewall (UFW) ────"

    # Install UFW if missing
    if ! command -v ufw &>/dev/null; then
        log_info "Installing UFW..."
        if command -v apt-get &>/dev/null; then
            apt-get update -qq && apt-get install -y -qq ufw
        elif command -v dnf &>/dev/null; then
            dnf install -y -q ufw
        elif command -v yum &>/dev/null; then
            yum install -y -q ufw
        elif command -v pacman &>/dev/null; then
            pacman -Sy --noconfirm ufw
        else
            bail "No supported package manager found — install UFW manually."
        fi
        log_ok "UFW installed."
    fi

    # Reset to defaults (non-interactive)
    echo "y" | ufw reset

    # Default policies: deny everything
    ufw default deny incoming
    ufw default deny outgoing

    # Allow outbound essentials (DNS, HTTP/S for updates, NTP)
    ufw allow out 53        # DNS
    ufw allow out 80/tcp    # HTTP (package updates)
    ufw allow out 443/tcp   # HTTPS
    ufw allow out 123/udp   # NTP

    # Allow the SSH port
    ufw allow in "${SSH_PORT}/tcp" comment "SSH (hardened)"
    ufw allow out "${SSH_PORT}/tcp" comment "SSH out"

    # Enable UFW
    echo "y" | ufw enable

    log_ok "UFW active — only port ${SSH_PORT}/tcp (SSH) is open for incoming."
    ufw status verbose
}

# ─── step 4: print summary ─────────────────────────────────────────────────────

print_summary() {
    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║              HARDENING COMPLETE                             ║${NC}"
    echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
    echo -e "${GREEN}║${NC}  SSH port        : ${CYAN}${SSH_PORT}${NC}                                     ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}  Auth method     : ${CYAN}Pubkey + passphrase${NC}                       ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}  Private key     : ${CYAN}~/.ssh/hardened${NC}                           ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}  Firewall        : ${CYAN}UFW active (deny all, allow ${SSH_PORT}/tcp)${NC} ${GREEN}║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${YELLOW}IMPORTANT — before closing this session:${NC}"
    echo -e "  Copy the one-liner below and run it on your ${CYAN}local machine${NC}."
    echo -e "  It installs your private key to ~/.ssh/hardened"
    echo ""
    echo -e "${RED}Do NOT close this session until you have confirmed access!${NC}"
    echo ""

    # Base64-encode the private key for easy single copy-paste
    local KEY_B64
    KEY_B64=$(base64 -w0 < "${TARGET_HOME}/.ssh/hardened")

    echo -e "${YELLOW}── Run this ONE command on your local machine ──${NC}"
    echo ""
    echo "echo '${KEY_B64}' | base64 -d > ~/.ssh/hardened && chmod 600 ~/.ssh/hardened && echo 'Done! Key installed.'"
    echo ""
    echo -e "${GREEN}Then connect with:${NC}"
    echo -e "  ${CYAN}ssh -p ${SSH_PORT} -i ~/.ssh/hardened ${TARGET_USER}@<server-ip>${NC}"
}

# ─── main ───────────────────────────────────────────────────────────────────────

main() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  Linux Shell Hardening Tool${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    preflight "$@"

    echo ""
    log_warn "This will overwrite your sshd_config and firewall rules."
    log_warn "A backup of sshd_config will be saved."
    echo ""
    read -rp "Continue? [y/N] " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        log_info "Aborted."
        exit 0
    fi

    generate_key
    echo ""
    configure_sshd
    echo ""
    configure_firewall
    echo ""
    print_summary
}

main "$@"
