#!/usr/bin/env bash
# lib/sshd.sh — hardened sshd_config (pubkey-only, custom port). Sourced by harden.sh.
set -euo pipefail

configure_sshd() {
    log_info "──── Configuring SSHD ────"

    # Back up current config (if it exists)
    if [[ -f "$SSHD_CONFIG" ]]; then
        run cp "$SSHD_CONFIG" "$SSHD_CONFIG_BACKUP"
        log_info "Backup saved to ${SSHD_CONFIG_BACKUP}"
    else
        log_warn "No existing sshd_config found — creating from scratch."
        SSHD_CONFIG_BACKUP="(none — fresh install)"
    fi

    # Detect sftp-server path
    SFTP_SERVER=""
    for p in /usr/lib/openssh/sftp-server /usr/libexec/openssh/sftp-server /usr/lib/ssh/sftp-server; do
        if [[ -x "$p" ]]; then
            SFTP_SERVER="$p"
            break
        fi
    done
    if [[ -z "$SFTP_SERVER" ]]; then
        SFTP_SERVER=$(find /usr -name sftp-server -type f 2>/dev/null | head -1)
    fi
    if [[ -n "$SFTP_SERVER" ]]; then
        SFTP_SUBSYSTEM="Subsystem sftp ${SFTP_SERVER}"
    else
        SFTP_SUBSYSTEM="# Subsystem sftp — sftp-server not found on this system"
        log_warn "sftp-server binary not found — SFTP subsystem disabled in config."
    fi

    # Cert-only mode: point AuthorizedKeysFile at a nonexistent path so only
    # CA-signed certs authenticate.
    local auth_keys_line="AuthorizedKeysFile .ssh/authorized_keys"
    if [[ "${CERT_ONLY:-0}" == "1" ]]; then
        auth_keys_line="AuthorizedKeysFile /etc/ssh/authorized_keys_disabled"
        log_warn "--cert-only: authorized_keys auth disabled, CA-signed certs only."
    fi

    # Build a clean hardened config
    write_file "$SSHD_CONFIG" <<EOF
# ─── Hardened sshd_config ── generated by harden.sh $(date +%Y-%m-%d) ──────────

# ── Network ──────────────────────────────────────────────────────────────────────
Port ${SSH_PORT}
AddressFamily inet
ListenAddress 0.0.0.0

# ── Authentication ───────────────────────────────────────────────────────────────
PermitRootLogin no
MaxAuthTries 3
MaxSessions 3

# Pubkey-only auth
PubkeyAuthentication yes
${auth_keys_line}

# Disable all other auth methods
PasswordAuthentication no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
# PAM needed for dynamic MOTD, limits, faillock — password auth stays disabled above
UsePAM yes
PermitEmptyPasswords no

# ── Security hardening ───────────────────────────────────────────────────────────
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
GatewayPorts no
PrintMotd no
TCPKeepAlive yes
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 30
StrictModes yes
IgnoreRhosts yes

# ── Logging ──────────────────────────────────────────────────────────────────────
SyslogFacility AUTH
LogLevel VERBOSE

# ── Allowed algorithms (modern only) ────────────────────────────────────────────
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519

# ── Certificate trust ────────────────────────────────────────────────────────
TrustedUserCAKeys /etc/ssh/ssh_ca.pub
RevokedKeys /etc/ssh/revoked_keys
HostCertificate /etc/ssh/ssh_host_ed25519_key-cert.pub

# ── Subsystems ───────────────────────────────────────────────────────────────────
${SFTP_SUBSYSTEM}
EOF

    # Ensure privilege separation directory exists
    if [[ ! -d /run/sshd ]]; then
        run mkdir -p /run/sshd
        run chmod 0755 /run/sshd
        log_ok "Created /run/sshd (privilege separation directory)."
    fi

    # Validate config before restarting (skipped in dry-run: config not written)
    if [[ "$DRY_RUN" == "1" ]]; then
        log_info "[DRY] skipping sshd -t validation"
    elif sshd -t -f "$SSHD_CONFIG"; then
        log_ok "sshd_config syntax is valid."
    else
        log_err "sshd_config syntax check FAILED — rolling back."
        if [[ -f "$SSHD_CONFIG_BACKUP" ]]; then
            run cp "$SSHD_CONFIG_BACKUP" "$SSHD_CONFIG"
            bail "Reverted to backup. Fix issues and re-run."
        else
            run rm -f "$SSHD_CONFIG"
            bail "Removed invalid config. Fix issues and re-run."
        fi
    fi

    # Restart (or start) sshd
    if systemctl is-active --quiet sshd 2>/dev/null; then
        run systemctl restart sshd
    elif systemctl is-active --quiet ssh 2>/dev/null; then
        run systemctl restart ssh
    elif systemctl list-unit-files sshd.service &>/dev/null; then
        run systemctl enable --now sshd
    elif systemctl list-unit-files ssh.service &>/dev/null; then
        run systemctl enable --now ssh
    else
        log_warn "Could not detect sshd service name — please start SSH manually."
    fi

    log_ok "SSHD configured and restarted on port ${SSH_PORT}."
}
