#!/usr/bin/env bash
# lib/sysctl.sh — kernel & network hardening via sysctl. Sourced by harden.sh.
set -euo pipefail

configure_sysctl() {
    log_info "──── Applying Kernel/Network Hardening (sysctl) ────"

    SYSCTL_CONF="/etc/sysctl.d/99-hardening.conf"

    write_file "$SYSCTL_CONF" <<'SYSEOF'
# ─── Network hardening ── generated by harden.sh ───────────────────────────────

# Disable IP forwarding (not a router)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# Enable SYN flood protection
net.ipv4.tcp_syncookies = 1

# Ignore ICMP redirects (prevent MITM)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Disable source routing (prevent spoofing)
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Enable reverse-path filtering (anti-spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcast requests (smurf attack prevention)
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# ── Kernel hardening ─────────────────────────────────────────────────────────

# Full ASLR
kernel.randomize_va_space = 2

# Hide kernel pointers from unprivileged users
kernel.kptr_restrict = 2

# Restrict dmesg to privileged users
kernel.dmesg_restrict = 1

# Restrict ptrace to parent processes only
kernel.yama.ptrace_scope = 1

# Restrict perf events to root
kernel.perf_event_paranoid = 3

# Hardlink/symlink protection
fs.protected_hardlinks = 1
fs.protected_symlinks = 1

# No core dumps from setuid binaries
fs.suid_dumpable = 0

# Log suspicious packets (martians)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable IPv6 if not needed (uncomment to disable)
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1
SYSEOF

    # Apply immediately
    if [[ "$DRY_RUN" == "1" ]]; then
        echo "[DRY] sysctl --system"
    else
        if ! sysctl --system > /dev/null 2>&1; then
            log_warn "sysctl --system reported errors — review ${SYSCTL_CONF}"
        fi
    fi

    log_ok "Kernel/network hardening applied via ${SYSCTL_CONF}."
}
